server:
  error:
    include-stacktrace: never
spring:
  application:
    name: salesmanager-supplier
  datasource:
    url: jdbc:h2:mem:supplierdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

##spring.application.name=salesmanager-customer

##  spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
##  spring.datasource.url=jdbc:mysql://localhost:3306/sample_dev_db
##  spring.datasource.username=sample_dev_db_user
##  spring.datasource.password=

##  spring.jpa.hibernate.ddl-auto=create
