server:
  error:
    include-stacktrace: never
spring:
  application:
    name: salesmanager-supplier
  h2:
    console.enabled: true
  data:
    web:
      pageable:
        size-parameter: 10
  datasource:
    url: jdbc:h2:mem:supplierdb;MODE=MySQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true